### ISSUE TITLE
Compiler crash when trying to compile simple program

### ISSUE THREAD

**Issue by alexzlov** [Sparrow-lang/sparrow#59]
**Hello, Lucian!**
I've tried to build sparrow on both linux (Windows linux subsytem, ubuntu) and Windows 10. On linux the build had completed successfully, but when I ran the compiler with simple program from the tests folder, I had got a segmentation fault.
Since I lack skills of using gdb, I decided to try to build sparrow compiler on windows. I've encountered some difficulties while generating Visual Studio project using cmake (llvm location, and boost libs - cmake wasn't able to find correct boost static libraries) and compiling solution in Visual Studio (needed to tweak settings regarding precompiled header StdInc.pch and to change compilation mode from "C" to "C++" in all the files that have ".c" extension). After that tweaks I finally got the binary for Sparrow compiler (there were installation error because of incorrect INSTALL_PREFIX somewhere in cmake configs). 
I copied SparrowImplicitLib folder into the directory with SparrowCompiler.exe and tried to compile Power.spr from the tests/Examples folder. And in that case I had crash too. I rebuilt the compiler again with "Release with debug symbols" configuration and tried to debug. It appears that error hides somewhere in `spr_parserIf_createParser ` function. I've attached two screenshots from my debug session in hope that You would suggest me, where to dig further.
Your project looks really interesting to me and I hope You would help me to resolve that crash so I could work through the example programs supplied in repository. 

Good luck and best wishes,
Alex

![debugsession1](https://user-images.githubusercontent.com/5283363/36781423-e2d9dfc2-1c86-11e8-8e16-efffc11f52e8.PNG)
![debugsession2](https://user-images.githubusercontent.com/5283363/36781427-e7512542-1c86-11e8-8119-d9d67a06437c.PNG)

**Comment by alexzlov** [comment]
Forgot to mention, that I built the master branch.

**Comment by lucteo** [comment]
Dear Alex,

Thank you very much for the interest in Sparrow. I am also very glad that you were able to compile this under Windows; I haven't tried for a long long time (actually, I tried last year, but at that time the old LLVM version I was stuck with didn't compile well on with latest versions of MSVC).

From the screenshots you attached, it seems like a memory corruption problem or, more probable, ABI incompatibility. Currently, the parser for Sparrow is written in Sparrow, and it uses LLVM IR for bootstraping. Somehow, when you compile the LLVM code (parserIf.llvm file) you are compiling against a different ABI than the rest of the compiler.

Can you please give me the following information:
* whether you are using 32 or 64 bit compilation -- Sparrow will only work on 64 bit at the moment
* what is the version of Ubuntu you are using, and what is the compiler version
* a complete configure & build log would be better

It would be great if you would be able to provide me with a docker image, so that I can reproduce this problem.

Speaking of which, you can directly use a docker container with Sparrow in it to run the examples on the repo: https://hub.docker.com/r/sparrowlang/sparrow/ (this one uses an ubuntu:16.04 for OS). You can also check the output of the latest docker build here: https://hub.docker.com/r/sparrowlang/sparrow/builds/butifzk2h3xgk9bnhwjeqtk/

On Windows, I would expect to have some other ABI incompatibilities, due to the fact that I haven't been testing on Windows for a long time. I guess I can start checking Windows builds again.

Thank you.

Best regards,
LucTeo

**Comment by alexzlov** [comment]
Hi, Lucian!
It seems that I misinformed you regarding linux build - actually it's O.K.
Previously for WSL linux build I used the same source directory as for the windows build, but the different folders for cmake conf and build files. I cloned sparrow repo again into another place and tried to make a new build from scratch and everything went flawlessly. It seems I did something stupid previous time :) .

So I think there is no reason for you to waste time looking through my logs, since the linux compiler is working. I've tried to compile some example programs and all of them worked except the nbody.spr and meteor.spr in tests/BenchmarksGame folder. These are compiled successfully but when I launched them they had crashed. GDB showed that crash occured in cStringLen function somewhere in the runtime library. But that is another case :)

> Currently, the parser for Sparrow is written in Sparrow, and it uses LLVM IR for bootstraping. 

Aha, now I understand the purpose of that giant parserIf.llvm file! Could you, please, briefly explain to me how that file was obtained (generated), so I could understand the bootstraping process more clearly?

> whether you are using 32 or 64 bit compilation -- Sparrow will only work on 64 bit at the moment

I'm using 64 bit only compilation in both cases. In case of windows build I've added just a couple of fixes in these places:
https://github.com/Sparrow-lang/sparrow/blob/master/src/SparrowCompiler/SparrowCompiler.cpp#L101
https://github.com/Sparrow-lang/sparrow/blob/master/src/SparrowCompiler/SparrowCompiler.cpp#L121
I just changed ...native() to ...string() to make the project compile because Visual Studio complained about incompatibilities between boost::filesystem::path::string_type and std::string.
Maybe that errors occured because I'm using a different boost version (1.66.0) ? Can these fixes be a possible source of parserIf.llvm crash on windows?

Looking forward to read your thesis to have fun and learn more about the language.

Cheers, Alex.

**Comment by lucteo** [comment]
Hi Alex

It's good to hear that Linux compilation works.

Bootstrapping:
Initially, all the Sparrow compiler was written in C++. So I had a SparrowCompiler binary that was working fine on my machine. Then I wrote the Sparrow parser, and compiled it with that binary; I recorded the output as a .llvm file. Then I made some more changes to the compiler, and plugged it into the compiler itself. Now, each time you compile the compiler you would need a 'llc' step to compile the .llvm file into an object file, that is linked against the target SparrowCompiler binary.
There is a misspelled CMake flag "BOOSTSTRAP_SPARROW" that you can enable when compiling Sparrow, to try to generate the .llvm file from the given source file. For this to work, another SparrowCompiler needs to be installed on the machine.
I was planning to move more and more parts of the compiler into Sparrow, to force me to write more Sparrow code, and therefore have a better user feel.

It is really good to hear that you are planning to read from the thesis. Please note however that things are slowly changing since the time the thesis was written (the compiler still hasn't reached version 1.0).  Currently I'm working towards removing classes completely in an effort to become more functional (but still imperative); this effort should simplify the language and improve the user experience -- given that OOP is still fashionable, this may sound counterintuitive, but there are a lot of good reasons to abandon OOP paradigms.

Please let me know if I can help you with anything.

Best regards,
LucTeo
